server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: commandes-v1
          uri: lb://MICROSERVICE-COMMANDES-V1
          predicates:
            - Path=/api/v1/commandes/**
          filters:
            - StripPrefix=2
            # Result: /api/v1/commandes/foo -> /commandes/foo (Perfect for Controller)

        - id: commandes-v2
          uri: lb://MICROSERVICE-COMMANDES-V2
          # Service V2 has @RequestMapping("/commandes-v2")
          # Incoming: /api/v2/commandes/**
          # We want: /commandes-v2/**
          predicates:
            - Path=/api/v2/commandes/**
          filters:
            - RewritePath=/api/v2/commandes/(?<segment>.*), /commandes-v2/$\{segment}

        - id: produits
          uri: lb://MICROSERVICE-PRODUIT
          predicates:
            - Path=/api/produits/**
          filters:
            - StripPrefix=1
            # Incoming: /api/produits
            # We want: /produits (Service has @RequestMapping("/produits"))
            # Strip 1: /produits (Perfect)
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
