server:
  port: 8082

spring:
  application:
    name: microservice-produit
  config:
    import: "optional:configserver:http://localhost:8888/"
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:sqlite:produits.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
